<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="01_function.cs" />
    <Compile Remove="02_mutable.cs" />
    <Compile Remove="03_oop1.cs" />
    <Compile Remove="03_oop2.cs" />
    <Compile Remove="03_oop3.cs" />
    <Compile Remove="04_class_basic1.cs" />
    <Compile Remove="04_class_basic2.cs" />
    <Compile Remove="04_class_basic3.cs" />
    <Compile Remove="05_private1.cs" />
    <Compile Remove="05_private2.cs" />
    <Compile Remove="06_property1.cs" />
    <Compile Remove="06_property2.cs" />
    <Compile Remove="06_property3.cs" />
    <Compile Remove="06_property4.cs" />
    <Compile Remove="06_property5.cs" />
    <Compile Remove="06_property6.cs" />
    <Compile Remove="06_property7.cs" />
    <Compile Remove="07_static1.cs" />
    <Compile Remove="07_static10.cs" />
    <Compile Remove="07_static11.cs" />
    <Compile Remove="07_static12.cs" />
    <Compile Remove="07_static2.cs" />
    <Compile Remove="07_static3.cs" />
    <Compile Remove="07_static4.cs" />
    <Compile Remove="07_static5.cs" />
    <Compile Remove="07_static6.cs" />
    <Compile Remove="07_static7.cs" />
    <Compile Remove="07_static8.cs" />
    <Compile Remove="07_static9.cs" />
    <Compile Remove="08_value_vs_reference0.cs" />
    <Compile Remove="08_value_vs_reference1.cs" />
    <Compile Remove="08_value_vs_reference2.cs" />
    <Compile Remove="08_value_vs_reference3.cs" />
    <Compile Remove="08_value_vs_reference4.cs" />
    <Compile Remove="09_string1.cs" />
    <Compile Remove="09_string2.cs" />
    <Compile Remove="09_string3.cs" />
    <Compile Remove="09_string4.cs" />
    <Compile Remove="10_method1_overloading1.cs" />
    <Compile Remove="10_method2_named_argument1.cs" />
    <Compile Remove="10_method3_optional_parameter1.cs" />
    <Compile Remove="Program.cs" />
    <Compile Remove="this1.cs" />
    <Compile Remove="this2.cs" />
    <Compile Remove="this3.cs" />
    <Compile Remove="wpf1.cs" />
    <Compile Remove="wpf2.cs" />
    <Compile Remove="wpf3.cs" />
    <Compile Remove="wpf4.cs" />
    <Compile Remove="wpf5.cs" />
    <Compile Remove="편의표기법.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="01_function.cs" />
    <None Include="02_mutable.cs" />
    <None Include="03_oop1.cs" />
    <None Include="03_oop2.cs" />
    <None Include="03_oop3.cs" />
    <None Include="04_class_basic1.cs" />
    <None Include="04_class_basic2.cs" />
    <None Include="04_class_basic3.cs" />
    <None Include="05_private1.cs" />
    <None Include="05_private2.cs" />
    <None Include="06_property1.cs" />
    <None Include="06_property2.cs" />
    <None Include="06_property3.cs" />
    <None Include="06_property4.cs" />
    <None Include="06_property5.cs" />
    <None Include="06_property6.cs" />
    <None Include="06_property7.cs" />
    <None Include="07_static1.cs" />
    <None Include="07_static10.cs" />
    <None Include="07_static11.cs" />
    <None Include="07_static12.cs" />
    <None Include="07_static2.cs" />
    <None Include="07_static3.cs" />
    <None Include="07_static4.cs" />
    <None Include="07_static5.cs" />
    <None Include="07_static6.cs" />
    <None Include="07_static7.cs" />
    <None Include="07_static8.cs" />
    <None Include="07_static9.cs" />
    <None Include="08_value_vs_reference0.cs" />
    <None Include="08_value_vs_reference1.cs" />
    <None Include="08_value_vs_reference2.cs" />
    <None Include="08_value_vs_reference3.cs" />
    <None Include="08_value_vs_reference4.cs" />
    <None Include="09_string1.cs" />
    <None Include="09_string2.cs" />
    <None Include="09_string3.cs" />
    <None Include="09_string4.cs" />
    <None Include="10_method1_overloading1.cs" />
    <None Include="10_method2_named_argument1.cs" />
    <None Include="10_method3_optional_parameter1.cs" />
    <None Include="Program.cs" />
    <None Include="this1.cs" />
    <None Include="this2.cs" />
    <None Include="this3.cs" />
    <None Include="wpf1.cs" />
    <None Include="wpf2.cs" />
    <None Include="wpf3.cs" />
    <None Include="wpf4.cs" />
    <None Include="wpf5.cs" />
    <None Include="편의표기법.cs" />
  </ItemGroup>

</Project>
